apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: default
  labels:
    migrated-from: app-engine
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: 'false'
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containers:
        - image: gcr.io/<YOUR-PROJECT>/default
          resources:
            limits:
              memory: 256Mi
              cpu: '1'
      serviceAccountName: <YOUR-PROJECT>@appspot.gserviceaccount.com
      containerConcurrency: 40
