apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ryomak
  labels:
    cloud.googleapis.com/location: asia-east1
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: 'false'
        autoscaling.knative.dev/maxScale: '1'
        autoscaling.knative.dev/minScale : '1'
    spec:
      containers:
        - image: gcr.io/ryomak/reatter
          resources:
            limits:
              memory: 512Mi
              cpu: '1'
      serviceAccountName: ryomak@appspot.gserviceaccount.com
      containerConcurrency: 40
